server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/feel-free-to-try?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
# MyBatis??
mybatis:
  # ???????
  typeAliasesPackage: com.huanshi.hsproject.entity
  # ??mapper?????????mapper.xml????
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # ?????????
  configLocation: classpath:mybatis/mybatis-config.xml
